RodFlix/Models/Account.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace RodFlix.Models
{
	public class Account
	{
		[Key]
		public int IdAccount { get; set; }
		[Required]
		[MaxLength(255)]
		public string Email { get; set; }
		[Required]
		[MaxLength(127)]
		public string Senha { get; set; }
		



	}
}

RodFlix/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using RodFlix.Data;
using RodFlix.Models;

namespace RodFlix.Controllers
{
	[BindProperties]
	public class LoginController : Controller
	{
		public readonly AppDbContext _db;
		private Account? conta;
		

		public LoginController(AppDbContext db)
		{
			_db = db;
		}
		#region "Pagina de Login"
		public IActionResult Index(string email, string senha)
		{
			bool logadoOuNao = CheckUpDeLoginGet(email, senha);

			if (logadoOuNao == false)
				return View();

			else
				return Redirect("/MainPage/Index/");
		}
		
		public bool CheckUpDeLoginGet(string email, string senha)
		{
			conta = _db.Account.Where(c => c.Email == email).FirstOrDefault();

			if (conta == null || conta.Email == null || conta.Senha == null)
				return false;

			else if (conta.Email != email || conta.Senha != senha)
				return false;

			else return true;
		}
		#endregion

		#region "Pagina de Cadastro"

		public IActionResult Cadastrar()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Cadastrar(Account Conta)
		{
			_db.Account.Add(Conta);
			_db.SaveChanges();
			return View();
		}

		#endregion


		
	}
}

RodFlix/Controllers/MainPageController.cs
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Mvc;
using RodFlix.Data;
using RodFlix.Models;

namespace RodFlix.Controllers
{
	[BindProperties]
	public class MainPageController : Controller
	{
		public readonly AppDbContext _db;
		
		public MainPageController (AppDbContext db)
		{
			_db = db;
		}	

		public IActionResult Index()
		{
			List<Movies> movies = _db.Movies.ToList();
			return View(movies);
		}


	}
}

RodFlix/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;

namespace RodFlix.Controllers
{
	public class MoviesController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

RodFlix/Controllers/TestingController.cs
using Microsoft.AspNetCore.Mvc;
using HtmlAgilityPack;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.Text;
using System.IO;



namespace RodFlix.Controllers
{
	public class TestingController : Controller
	{

		public static async Task<string> CallUrl(string fullUrl)
		{
			HttpClient client = new HttpClient();
			var response = await client.GetStringAsync(fullUrl);
			return response;

		}
		
		public IActionResult Index()
		{
			string url = "https://en.wikipedia.org/wiki/List_of_programmers";
			var response = CallUrl(url).Result;
			return View();
		}
		/*
		private List<string> ParseHtml(string html)
		{
			HtmlDocument htmlDoc = new HtmlDocument();
			htmlDoc.LoadHtml(html);

			var programmerLinks = htmlDoc.DocumentNode.Descendants("li").
				Where(node => !node.GetAttributeValue("class","").Contains("tocsection")).ToList();

			List<string> wikiLink = new List<string>();

			foreach (var link in programmerLinks)
			{
				if (link.FirstChild.Attributes.Count > 0) wikiLink.Add("");
			}

		}
		*/



	}


}

RodFlix/Views/Login/Cadastrar.cshtml
@model Account
@{
	
}
<head>

	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapVapor.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>

	<form method="post">

		<div class="border p-3 m-5 ">
			<div class="row pb-3">
				<h1 class="text-primary">Cadastrar</h1>
				
			</div>

			<div class="mb-3 row p-1">
				<label asp-for="Email" class="p-0">Email</label>
				<input asp-for="Email" class="form-control">
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>

			<div class="mb-3 row p-1">
				<label asp-for="Senha" class="p-0">Senha</label>
				<input asp-for="Senha" class="form-control">
				<span asp-validation-for="Senha" class="text-danger"></span>
			</div>

			<div class="row">
				<div class="col-2">
					<button type="submit" class="btn btn-primary form-control ml-1" style="width:150px">Cadastrar</button>
				</div>

				<div class="col-7">
					<button class="btn btn-primary" style="width:150px"> <a asp-controller="Login" asp-action="Index">Logar</a> </button>
				</div>

				
			</div>
		</div>
	</form>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>


</body>

RodFlix/Views/Login/Index.cshtml
@model Account
@{
	
}
<head>
	
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapVapor.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>

	<form method="post">

		<div class="border p-3 m-5 ">
			<div class="row pb-2">
				<h1 class="text-primary">Login</h1>
				<hr />
			</div>
		
			<div class="mb-3 row p-1">
				<label asp-for="Email" class="p-0">Email</label>
				<input asp-for="Email" class="form-control">
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>

			<div class="mb-3 row p-1">
				<label asp-for="Senha" class="p-0">Senha</label>
				<input asp-for="Senha" class="form-control">
				<span asp-validation-for="Senha" class="text-danger"></span>
			</div>

			<div class="row">
				<div class="col-2">
					<button type="submit" class="btn btn-primary form-control ml-1" style="width:150px">Entrar</button>
				</div>

				<div class="col-7">
					<button class="btn btn-primary" style="width:150px"> <a asp-controller="Login" asp-action="Index">Return</a> </button>
				</div>

				<div class="col-3">
					<label>Não possui conta ainda?</label>
					@Html.ActionLink("Cadastre-se","Cadastrar","Login")
				</div>
			</div>
		</div>
	</form>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
</body>

RodFlix/Views/MainPage/Index.cshtml
@model List<Movies>
@{
	bool variavel = false;
	
}
<head>
	<link rel="stylesheet" href="~/css/MainPage/Index/Index.css" />
</head>

<body>

	<h1 class="text-primary">
		<strong class="text-white ">Filmes</strong>
	</h1>
			
	
	<br/>
	<br/>
	<br/>
	@if (variavel == true)
	{
		<h2>
			CADE O MEU PAL??? AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!!!
		</h2>
	}

	<div class="main-content p-0 m-0">

		<div class="container p-0">

			<div id="" class="slider">
				<ul class="films-list">
					@foreach (var obj in Model)
					{
						<li>
							<div class="movie-element bg-primary text-white">

								<img class="movie-image"src="~/Images/NetFlixo.jpg" style="max-height:192px; max-width:240px;">
								<br/>
								<div class="movie-element" >
									<p class="movie-title">@obj.Title</p>
									<br/>
									@if(obj.LengthMinutes % 2 == 0)
									{
										<p>Par e.e</p>
									}
									<p class="movie-length">@obj.LengthMinutes minutos</p>
								</div>
								<br/>
								<br/>

							</div>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

</body>


<script src="~/js/MainPage/Index/Index.js"></script>

RodFlix/Views/Movies/Index.cshtml
@model List<Movies>

RodFlix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RodFlix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapSuperHero.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RodFlix.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Reset.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid p-0">
                <div class="bg-white pt-2 h-100 ">
                    <a class="navbar-brand text-primary " asp-area="" asp-controller="Movies" asp-action="Index"><strong>RODFLIX</strong></a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MainPage" asp-action="Index">Inicio</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index">Logar e/ou cadastrar outra conta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>